name: Google Cloud Run Deployment

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: europe-west1
  SERVICE_NAME: kontrakt-web

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
      - run: gcloud auth configure-docker
      # Build the Docker image
      - name: Build
        run: docker build . --tag eu.gcr.io/$PROJECT_ID/$SERVICE_NAME
      - name: Publish
        run: docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME
      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" \
            --platform "managed" \
            --allow-unauthenticated
